kernel:
  image: linuxkit/kernel:4.9.70
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:9250948d0de494df8a811edb3242b4584057cfe4
  - linuxkit/runc:abc3f292653e64a2fd488e9675ace19a55ec7023
  - linuxkit/containerd:e58a382c33bb509ba3e0e8170dfaa5a100504c5b
  - linuxkit/ca-certificates:de21b84d9b055ad9dcecc57965b654a7a24ef8e0
onboot:
  - name: sysctl
    image: linuxkit/sysctl:ce3bde5118a41092f1b7048c85d14fb35237ed45
  - name: netdev
    image: linuxkit/modprobe:1a192d168adadec47afa860e3fc874fbc2a823ff
    # https://github.com/linuxkit/linuxkit/blob/master/docs/platform-rpi3.md#networking
    command: ["modprobe", "smsc95xx"]
  - name: dhcpcd
    image: linuxkit/dhcpcd:0d59a6cc03412289ef4313f2491ec666c1715cc9
    # Halts until dhcpcd can resolve ip address
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: format
    image: linuxkit/format:e945016ec780a788a71dcddc81497d54d3b14bc7
  - name: mount-lib
    image: linuxkit/mount:b346ec277b7074e5c9986128a879c10a1d18742b
    command: ["/usr/bin/mountie", "/var/lib"]
    # Mount /var/log to the first found disk device
  - name: mount-log
    image: linuxkit/mount:b346ec277b7074e5c9986128a879c10a1d18742b
    command: ["/usr/bin/mountie", "/var/log"]

services:
  - name: getty
    image: linuxkit/getty:22e27189b6b354e1d5d38fc0536a5af3f2adb79f
    env:
    # Makes the terminal open without password prompt
     - INSECURE=true
  - name: ntpd
    image: linuxkit/openntpd:536e5947607c9e6a6771957c2ff817230cba0d3c
  - name: dhcpcd
    image: linuxkit/dhcpcd:0d59a6cc03412289ef4313f2491ec666c1715cc9 
  
  - name: eliotd
    image: ernoaapa/eliotd:v0.2.0
    command: ["/eliotd", "--debug", "--grpc-api-listen", "0.0.0.0:5000"]
    capabilities:
      - all
    net: host
    pid: host
    runtime:
      mkdir: ["/var/lib/volumes"]
    binds:
      - /containers:/containers
      - /var/lib/volumes:/var/lib/volumes
      - /var/lib/containerd:/var/lib/containerd
      - /run/containerd:/run/containerd
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/machine-id:/etc/machine-id
      - /var/log:/var/log # To be able to serve default containers logs through api
      - /tmp:/tmp # To be able to read temporary fifo log files
files:
  - path: /etc/issue
    contents: "wellcome to EliotOS"
  - path: /etc/machine-id
    contents: "todo-generate"
    mode: "0600"
trust:
  org:
    - linuxkit
