defaults: &defaults
  docker:
    - image: circleci/golang:1.10
  working_directory: /go/src/github.com/ernoaapa/eliot-os

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install tools
          command: |
            go get -u github.com/linuxkit/linuxkit/src/cmd/linuxkit
            go get -u github.com/estesp/manifest-tool

      - run:
          name: Build linuxkit package images
          command: |
            cd pkg
            make forcebuild
      - run:
          name: Build linuxkit
          command: |
            mkdir dist/
            curl --fail -X POST --data-binary @rpi3.yml http://build.eliot.run/linuxkit/eliot-os-raspberrypi3/build/rpi3 | tar xv -C dist
            find ./dist/initrd.uimg -type f -size +20M | grep -q "."

  publish-packages:
    <<: *defaults
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install tools
          command: |
            go get -u github.com/linuxkit/linuxkit/src/cmd/linuxkit
            go get -u github.com/estesp/manifest-tool

      - run:
          name: Login Docker hub
          command: echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
    
      - run:
          name: Build & push linuxkit package images
          command: |
            cd pkg
            make forcepush
  
  publish-linuxkit:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Install tools
          command: go get github.com/tcnksm/ghr

      - run:
          name: Build RasperryPI3 distro
          command: |
            mkdir dist/
            curl --fail -X POST --data-binary @rpi3.yml http://build.eliot.run/linuxkit/eliot-os-raspberrypi3/build/rpi3 | tar xv -C dist
            ghr -token $GITHUB_TOKEN -username $CIRCLE_PROJECT_USERNAME -repository $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG dist/

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            tags:
              ignore:
                - /.*/

      - publish-packages:
          filters:
            branches:
              only: master

      - publish-linuxkit:
          # Don't run when branches updates, only when tags get created
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /v.*/